---
title: System.IdentityModel.IdentityModelAsyncCallbackThrewException
ms.date: 03/30/2017
ms.assetid: e4fc924f-3b9e-44f5-97e4-b3a4bb855d89
ms.openlocfilehash: 85a460640f6a2358bcf4986891e1fb5133a1d24e
ms.sourcegitcommit: bc293b14af795e0e999e3304dd40c0222cf2ffe4
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 11/26/2020
ms.locfileid: "96254121"
---
# <a name="systemidentitymodelidentitymodelasynccallbackthrewexception"></a>System.IdentityModel.IdentityModelAsyncCallbackThrewException

System.IdentityModel.IdentityModelAsyncCallbackThrewException  
  
## <a name="description"></a>Descripción  

 Una devolución de llamada asincrónica produjo una excepción.  
  
## <a name="see-also"></a>Vea también

- [Seguimiento](index.md)
- [Uso del seguimiento para solucionar problemas de su aplicación](using-tracing-to-troubleshoot-your-application.md)
- [Administración y diagnóstico](../index.md)
